### ISSUE TITLE
Cannot search for project or tags "No 'Access-Control-Allow-Origin' header"

### ISSUE THREAD

**Issue by clemens-tolboom** [Lullabot/drupalorg-issues#5]
When changing project I get
## Chrome

> XMLHttpRequest cannot load  https://www.drupal.org/entityreference/autocomplete/single/field_project/node/project_issue/NULL/Gra. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8000' is therefore not allowed access.
## Firefox

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://www.drupal.org/entityreference/autocomplete/single/field_project/node/project_issue/NULL/Gra. This can be fixed by moving the resource to the same domain or enabling CORS.

This happens on http://lullabot.github.io/drupalorg-issues/#/board and localhost

**Comment by justafish** [comment]
Issue opened on drupal.org to allow this https://www.drupal.org/node/2405871
