### ISSUE TITLE
Add number of issues to the top of each column

### ISSUE THREAD

**Issue by lewisnyman** [Lullabot/drupalorg-issues#6]
Hi! This is awesome!

The panel that includes the number of issues loaded get's pushed to the bottom of the list, which means it's easily missed.

Maybe it could work better as a badge at the top of the column? I've mocked it up quickly
![drupal_org_issues](https://cloud.githubusercontent.com/assets/632390/5692949/7ee9cf1c-9909-11e4-8485-7a962c6a1c78.png)

**Comment by justafish** [comment]
It's actually not the number of issues loaded in that panel, it's the number of issues remaining **not** loaded (since we don't want to crash the browser). Maybe it would be useful as a combined total? Issues loaded + Issues not loaded?
